version: '3'
services:
  postgres:
    image: 'postgres:9.6-alpine'
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data



  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"
    depends_on:
      - postgres


  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres


  cloud9:
    image: sapk/cloud9
    volumes:
      - .:/workspace
    ports:
      - 8181:8181
    command: --auth root:root
